# Generated by Django 3.1.3 on 2020-11-24 21:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=32, verbose_name='Account')),
                ('ip', models.CharField(max_length=30, verbose_name='IP Address')),
                ('ip_addr', models.CharField(max_length=30, verbose_name='IP Geographical Address')),
                ('character', models.CharField(max_length=32, verbose_name='Character')),
            ],
            options={
                'verbose_name': 'Visit User Information',
                'verbose_name_plural': 'Visit User Information',
            },
        ),
        migrations.CreateModel(
            name='DayNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=django.utils.timezone.now, verbose_name='日期')),
                ('count', models.IntegerField(default=0, verbose_name='visit Num')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padmin.userip', verbose_name='userIP')),
            ],
            options={
                'verbose_name': 'User daily visit Num',
                'verbose_name_plural': 'User daily visit Num',
            },
        ),
    ]
