# Generated by Django 3.1.3 on 2020-11-24 21:54

from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=256, validators=[student.models.validate_pwd])),
                ('email', models.EmailField(max_length=254)),
                ('password_en', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Student_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('grade', models.CharField(default=2020, max_length=10)),
                ('sex', models.CharField(default='男', max_length=5)),
                ('education', models.CharField(default='本科', max_length=10)),
                ('school', models.CharField(default='南方科技大学', max_length=50)),
                ('major', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'db_table': 'Student_Information',
            },
        ),
    ]
