# Generated by Django 3.1.3 on 2020-11-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_information',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_information',
            name='major',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
